---
# vars file for djangoApache2Deploy
USER: ""
PROJECT_NAME: ""
LOCAL_USER: ""
LOCAL_PROJECT_NAME: ""
DOMAIN: ""
APACHE_USER: www-data
APACHE_CONF_FILES_PATH: /etc/apache2/sites-available/
SERVER_ADMIN: ""
DEFAULT_APACHE_HTDOCS_DIR: /var/www/html
SITE_NAME: "{{DOMAIN}}"
DOCUMENT_ROOT: ""
VIRTUALENV_PATH: "/home/{{USER}}/.virtualenvs/{{PROJECT_NAME}}"
SERVER_NAME: "{{DOMAIN}}"
WSGI_APP_PATH: ""
MEDIA_PATH: "{{DEFAULT_APACHE_HTDOCS_DIR}}/{{SERVER_NAME}}/media"
STATIC_PATH: "{{DEFAULT_APACHE_HTDOCS_DIR}}/{{SERVER_NAME}}"
LOCAL_STATIC_FILES_PATH: ""
